name: Generate Podcast Feeds
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruyaml

      - name: Run Feed Generator
        run: python feed.py

      - name: Push Repo
        run: |
          git config --global user.name "tkats1993"
          git config --global user.email "mitsokleas@gmail.com"
          git add .
          git commit -m "Modified Feed"
          git push

       
       
       
